version: '3'

services:
  db:
    image: postgres:alpine
    volumes:
      - nextcloud-db:/var/lib/postgresql/data
    environment: 
      - POSTGRES_DB_FILE=/run/secrets/nc_postgres_db
      - POSTGRES_USER_FILE=/run/secrets/nc_postgres_user
      - POSTGRES_PASSWORD_FILE=/run/secrets/nc_postgres_password
    secrets:
      - nc_postgres_db
      - nc_postgres_password
      - nc_postgres_user
    deploy:
        replicas: 1
        placement:
            constrainsts:
                - node.labels.disk == hdd
        restart_policy:
            condition: on-failure
            max_attempts: 1
    networks: 
        - nextcloud-net
  app:
    image: nextcloud:fpm-alpine
    volumes:
      - nextcloud-html:/var/www/html
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB_FILE=/run/secrets/nc_postgres_db
      - POSTGRES_USER_FILE=/run/secrets/nc_postgres_user
      - POSTGRES_PASSWORD_FILE=/run/secrets/nc_postgres_password
    depends_on:
      - db
    deploy:
        replicas: 1
        placement:
            constraints:
                - node.labels.disk == hdd
        restart_policy:
            condition: on-failure
            max_attempts: 1
    networks: 
        - nextcloud-net

  web:
    image: pmelchi/nextcloud-web:example
    volumes:
      - nextcloud-html:/var/www/html:ro
    environment:
      - VIRTUAL_HOST=
      - LETSENCRYPT_HOST=
      - LETSENCRYPT_EMAIL=
    depends_on:
      - app
    deploy:
        replicas: 1
        placement:
            constraints: 
                - node.labels.disk === hdd
        restart_policy:
            condition: on-failure
            max_attempts: 1
    networks:
        - proxy-tier
        - default

  proxy:
    image: pmelchi/nextcloud-proxy:10G
    ports:
      - 80:80
      - 443:443
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    volumes:
      - certs:/etc/nginx/certs:ro
      - vhost.d:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - proxy-tier

  letsencrypt-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: always
    volumes:
      - certs:/etc/nginx/certs
      - vhost.d:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - proxy-tier
    depends_on:
      - proxy

volumes:
  nextcloud-db:
    external: true
  nextcloud-html:
    external: true
  certs:
  vhost.d:
  html:

networks:
    proxy-tier:
    nextcloud-net:

secrets:
  nc_postgres_db:
    external: true
  nc_postgres_password:
    external: true
  nc_postgres_user:
    external: true