version: '3'

services:
  db:
    image: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - nextcloud-db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=
    env_file:
      - db.env
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.disk == hdd
      restart_policy:
        condition: on-failure
        max_attempts: 1
    networks:
      - nextcloud-net

  app:
    image: nextcloud:fpm-alpine
    volumes:
      - nextcloud-html:/var/www/html
    environment:
      - MYSQL_HOST=db
    env_file:
      - db.env
    depends_on:
      - db
    deploy:
      replicas: 1
      placement:
          constraints:
            - node.labels.disk == hdd
      restart_policy:
        condition: on-failure
        max_attempts: 1
    networks:
      - nextcloud-net

volumes:
  nextcloud-db:
    external: true
  nextcloud-html:
    external: true

networks:
  nextcloud-net: