version: '3.7'

services:
  db:
    image: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
      - db:/var/lib/mysql
    secrets:
      - source: nextcloud-mysql-password
        target: MYSQL_PASSWORD_FILE
      - source: nextcloud-mysql-root-password
        target: MYSQL_ROOT_PASSWORD_FILE
      - source: nextcloud-mysql-database
        target: MYSQL_DATABASE_FILE
      - source: nextcloud-mysql-user
        target: MYSQL_USER_FILE

volumes:
  db:
secrets:
  nextcloud-mysql-password:
    external: true
  nextcloud-mysql-root-password:
    external: true
  nextcloud-mysql-database:
    external: true
  nextcloud-mysql-user:
    external: true