version: '3'

services:
  db:
    image: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD_FILE= /run/secrets/nextcloud-mysql-root-password
      - MYSQL_PASSWORD_FILE= /run/secrets/nextcloud-mysql-password
      - MYSQL_DATABASE_FILE= /run/secrets/nextcloud-mysql-database
      - MYSQL_USER_FILE= /run/secrets/nextcloud-mysql-user
volumes:
  db: