version: '3'
services:
  nginx:
    image: nginx:1.15-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - certbot-conf:/etc/letsencrypt
      - certbot-www:/var/www/certbot 
    deploy:
      replicas: 1
      placement:
          constraints: 
              - node.labels.function == gateway
      restart_policy:
          condition: on-failure
          max_attempts: 1
  certbot:
    image: certbot/certbot
    volumes: 
      - certbot-conf:/etc/letsencrypt
      - certbot-www:/var/www/certbot
    deploy:
      replicas: 1
      placement:
          constraints: 
              - node.labels.function == gateway
      restart_policy:
          condition: on-failure
          max_attempts: 1
volumes:
  certbot-conf:
  certbot-www: